name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:

  build:
    name: Build and test on go ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    strategy:
       matrix:
         go_version: [1.17]
    steps:
    - name: Install Go ${{ matrix.go_version }}
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Go Version
      run: go version

    - name: Go Dependencies
      run: go get -v -t -d ./...

    - name: Go Test
      run: go test ./... -count=1 -race -cover

    - name: Build
      if: matrix.go_version == 1.17
      run: go build -v ./...